import pygame

# 0:초기화 / 1:다음 게임 준비 / 2: 게임 시작 / 3: 플레이 / 4: 게임 종료
GAME_STATE_INIT = 0
GAME_STATE_READY = 1
GAME_STATE_START = 2
GAME_STATE_PLAYING = 3
GAME_STATE_OVER = 4


FPS = 60

# 스크린 전체 크기 지정
SCREEN_WIDTH = 588
SCREEN_HEIGHT = 1060
#SCREEN_WIDTH = 575
#SCREEN_HEIGHT = 944

LAND_TOP_HEIGHT = SCREEN_HEIGHT * 0.5
LAND_BOTTOM_HEIGHT = LAND_TOP_HEIGHT + 179

LEFT_SPAWN_POSITION = (SCREEN_WIDTH * 0.01, LAND_TOP_HEIGHT + 100)
RIGHT_SPAWN_POSITION = (SCREEN_WIDTH - (SCREEN_WIDTH * 0.4), LAND_TOP_HEIGHT + 55)

MAX_WORD_LEN = 5

# 커스텀 이벤트 생성
EVENT_SOCKET_MSG = pygame.USEREVENT+1

# socket msg code
MSG_CODE_COMMENT = 1
MSG_CODE_LIKE = 2
MSG_CODE_DONATION = 3
MSG_CODE_SHARE = 4
MSG_CODE_QUIT = 5
MSG_CODE_NOTICE = 6

NPC_DOG_STATE_IDLE = 0
NPC_DOG_STATE_WALK = 1
NPC_DOG_STATE_RUN = 2
NPC_DOG_STATE_JUMP = 3
NPC_DOG_STATE_SLIDE = 4
NPC_DOG_STATE_HURT = 5