import pygame


dog_images = []
def import_dog_images(size):
    # 오른쪽을 보고있는 강아지 이미지
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_1.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_2.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_3.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_4.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_5.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_6.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_7.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_8.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_9.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_10.png'), size))

    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_1.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_2.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_3.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_4.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_5.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_6.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_7.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_8.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_9.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_10.png'), size))

    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_1.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_2.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_3.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_4.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_5.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_6.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_7.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_8.png'), size))

    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_1.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_2.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_3.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_4.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_5.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_6.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_7.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_8.png'), size))

    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_1.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_2.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_3.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_4.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_5.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_6.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_7.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_8.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_9.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_10.png'), size))

    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_1.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_2.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_3.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_4.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_5.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_6.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_7.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_8.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_9.png'), size))
    dog_images.append(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_10.png'), size))

    # 왼쪽을 보고있는 강아지 이미지
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_8.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_9.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_idle_10.png'), size), True, False))

    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_8.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_9.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_walk_10.png'), size), True, False))

    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_run_8.png'), size), True, False))

    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_jump_8.png'), size), True, False))

    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_8.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_9.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_slide_10.png'), size), True, False))

    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_8.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_9.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/dog/dog_hurt_10.png'), size), True, False))


cat_images = []
def import_cat_images(size):
    # 오른쪽을 보고있는 강아지 이미지
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_1.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_2.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_3.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_4.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_5.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_6.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_7.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_8.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_9.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_10.png'), size))
    
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_1.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_2.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_3.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_4.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_5.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_6.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_7.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_8.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_9.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_10.png'), size))

    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_1.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_2.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_3.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_4.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_5.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_6.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_7.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_8.png'), size))
    
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_1.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_2.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_3.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_4.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_5.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_6.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_7.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_8.png'), size))

    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_1.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_2.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_3.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_4.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_5.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_6.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_7.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_8.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_9.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_10.png'), size))

    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_1.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_2.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_3.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_4.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_5.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_6.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_7.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_8.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_9.png'), size))
    cat_images.append(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_10.png'), size))

    # 왼쪽을 보고있는 강아지 이미지
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_1.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_2.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_3.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_4.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_5.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_6.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_7.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_8.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_9.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_idle_10.png'), size), True, False))

    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_1.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_2.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_3.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_4.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_5.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_6.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_7.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_8.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_9.png'), size), True, False))
    cat_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_walk_10.png'), size), True, False))

    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_run_8.png'), size), True, False))
    
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_jump_8.png'), size), True, False))

    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_8.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_9.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_slide_10.png'), size), True, False))

    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_1.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_2.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_3.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_4.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_5.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_6.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_7.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_8.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_9.png'), size), True, False))
    dog_images.append(pygame.transform.flip(pygame.transform.scale(pygame.image.load('game/res/character/cat/cat_hurt_10.png'), size), True, False))


def import_sound():
    sound_map = {}
    donation_sound = pygame.mixer.Sound("game/res/sound/donation.mp3")
    donation_sound.set_volume(0.4)
    sound_map['donation'] = donation_sound
    stage_clear_sound = pygame.mixer.Sound("game/res/sound/stage_clear.mp3")
    stage_clear_sound.set_volume(0.4)
    sound_map['stage_clear'] = stage_clear_sound
    bonus_time_tts = pygame.mixer.Sound("game/res/sound/bonus_time_tts.wav")
    bonus_time_tts.set_volume(0.4)
    sound_map['bonus_time_tts'] = bonus_time_tts
    return sound_map
    